name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Google Cloud SDK
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }} # base64로 인코딩된 JSON 키
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} # 프로젝트 ID도 secret에 저장
        run: |
          # base64로 인코딩된 키를 디코드하여 JSON 파일로 저장
          echo "$GCP_SA_KEY" | base64 --decode > $HOME/gcp-key.json
          # Google Cloud 인증
          gcloud auth activate-service-account --key-file $HOME/gcp-key.json
          # 프로젝트 설정
          gcloud config set project $GCP_PROJECT_ID

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-dnd-app .

      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-dnd-app
